### ISSUE TITLE
performance issue

### ISSUE THREAD

**Issue by vatelzh** [ceph/ceph-iscsi-cli#58] opened 2017-12-11 09:44 UTC
In my environment, I create 46 disks, 37 hosts, and I found gwcli is started really slowly...
time gwcli ls > /dev/null

real	0m7.003s
user	0m2.570s
sys	0m0.551s

time ceph -s > /dev/null

real	0m0.448s
user	0m0.390s
sys	0m0.038s

**Comment by vatelzh** [comment] 2017-12-11 12:01
Print the timestamp, found that refresh disk information using 7s :(
2017-12-11 06:54:57,622 DEBUG    [storage.py:49:refresh()] Refreshing disk information from the config object
2017-12-11 06:55:04,726 DEBUG    [storage.py:56:refresh()] Refreshing disk information end   <----add this line after disk refresh

**Comment by pcuzner** [comment] 2017-12-12 03:38
I suspect this is due to the lookups and repeated ioctx's that get generated in the DIsk.get_meta_data_tcmu method. Could you add similar debug messages into this method to confirm?

**Comment by vatelzh** [comment] 2017-12-12 04:59
`def get_meta_data_tcmu(self):
        """
        query the rbd to get the features and size of the rbd
        :return:
        """
        self.logger.debug("start rados...")
        with rados.Rados(conffile=settings.config.cephconf) as cluster:
            self.logger.debug("start open_ioctx...")
            with cluster.open_ioctx(self.pool) as ioctx:
                self.logger.debug("start rbd.Image...")
                with rbd.Image(ioctx, self.image) as rbd_image:
                    self.size = rbd_image.size()
                    self.size_h = human_size(self.size)
                    self.features = rbd_image.features()
                    self.feature_list = self._get_features()
                self.logger.debug("end rbd.Image...")
            self.logger.debug("end open_ioctx...")
        self.logger.debug("end rados...")`

That's the debug info I added.

2017-12-11 23:54:52,715 DEBUG    [storage.py:480:get_meta_data_tcmu()] start rados...
2017-12-11 23:54:52,733 DEBUG    [storage.py:482:get_meta_data_tcmu()] start open_ioctx...
2017-12-11 23:54:52,734 DEBUG    [storage.py:484:get_meta_data_tcmu()] start rbd.Image...
2017-12-11 23:54:52,807 DEBUG    [storage.py:490:get_meta_data_tcmu()] end rbd.Image...
2017-12-11 23:54:52,807 DEBUG    [storage.py:491:get_meta_data_tcmu()] end open_ioctx...
2017-12-11 23:54:52,811 DEBUG    [storage.py:492:get_meta_data_tcmu()] end rados...

Each disk costs about 100ms, and I have more than 50 disks. So this can explain why gwcli command is slowly.

**Comment by vatelzh** [comment] 2017-12-14 08:03
@pcuzner Any idea about how to improve it? Or that's how it was designed?

**Comment by pcuzner** [comment] 2017-12-14 08:45
That's how it was designed - but for larger deployments its a problem! We need to get away from the serial device discovery, and adopt a producer/consumer model to get the device stats in parallel. I can look into that next week.

**Comment by vatelzh** [comment] 2017-12-14 09:12
that will be great :)

**Comment by pcuzner** [comment] 2017-12-18 02:54
@vatelzh can you use the reduce_startup_time branch and confirm that this addresses your issue. The default is to run 8 concurrent 'scans', but this can be changed by gwcli -t <n> for larger clusters (and more capable gateways!)

**Comment by vatelzh** [comment] 2017-12-18 04:02
@pcuzner Great, will try it later.

**Comment by vatelzh** [comment] 2017-12-18 04:46
Create 50 disks, and execute gwcli command:
without patch:
time gwcli ls > /dev/null

real	0m5.940s
user	0m2.842s
sys	0m0.588s

apply patch with scan_threads=4:
time gwcli -t 4 ls > /dev/null

real	0m3.775s
user	0m1.280s
sys	0m0.199s

apply patch with scan_threads=8:
time gwcli -t 8 ls > /dev/null

real	0m2.202s
user	0m1.311s
sys	0m0.227s

apply patch with scan_threads=16:
time gwcli -t 16 ls > /dev/null

real	0m1.669s
user	0m1.213s
sys	0m0.182s

comment this line in storage.py self.get_meta_data_tcmu():
time gwcli ls > /dev/null

real	0m1.222s
user	0m1.018s
sys	0m0.144s

@pcuzner 
Performance result is acceptable by  increase threads.

**Comment by pcuzner** [comment] 2017-12-21 21:23
PR #65 raised to merge this feature

**Comment by pcuzner** [comment] 2018-01-18 01:03
PR merged

**Closed by pcuzner** 2018-01-18 01:03 UTC
